### ISSUE TITLE
editing offed price hit alarm directly on the alarm list

### ISSUE THREAD

**Issue by algazarra** [andrefbsantos/boilr#105]
tried to edit an offed alarm on the alarm list. after entering lower limit, got a warning at screen bottom saying the alarm couldn't be saved because the upper limit was lower than last price. after the error the alarm disappeared from the list.

is it possible to change this behavior?
I'd let the user edit the alarm, and the warning would only appear if the user tried to turn on an alarm where limits weren't correctly set. Either way, always let the user edit.

**Comment by dllud** [comment]
> after the error the alarm disappeared from the list

That shouldn't happen, the alarm should stay on the list with the previous value. On my device it behaves correctly and stays on the list. Please try reproducing this on the apk I am sending you now.

**Comment by algazarra** [comment]
this apk (rc15) seems to be unstable. check #106
the only thing I haven't done yet is deleting all app data and uninstall + fresh install.

**Comment by dllud** [comment]
Confirmed non bug. Issue was sign of some other bug on the DB perhaps.

**Comment by algazarra** [comment]
until when will the user have to delete app data with each update?
