### ISSUE TITLE
Extremely unstable after update

### ISSUE THREAD

**Issue by algazarra** [andrefbsantos/boilr#106]
Simply updating to the rc15 made Boilr very unstable. Trying to create or edit an alarm is enough to break Boilr.

After force stopping, the problem persisted. I'm trying rebooting the phone.

**Comment by algazarra** [comment]
Didn't work. My only option is to delete all my alarms and see if it fixes. BTW I'm using an average of 7 alarms. This is not good

**Comment by dllud** [comment]
This issue had something to do with an incoherent state in the DB and wasn't due to the update. If it ever happens again please open a new issue referencing a DB issue and try to explain all steps needed to reproduce it.
