### ISSUE TITLE
Triggered alarm + menu button dead loop

### ISSUE THREAD

**Issue by algazarra** [andrefbsantos/boilr#110]
When an alarm triggers, if you press the menu button there's no way to turn off the alarm. It keeps ringing on and on until force stopped.

**Comment by dllud** [comment]
Sure there is. Just long-click the menu button, navigate back to Boilr's triggered alarm activity and click "Off".

**Comment by algazarra** [comment]
Yes but if you go back to Boilr by clicking it's icon or through the notification you get stuck on a dead loop.
