### ISSUE TITLE
after alarm off - prices don't update

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#12]
after offing an alarm, last and bound prices display 0000. alarm is still set to trigger at XXX price, but the display doesn't update and defaults to zero.

**Comment by cicardia** [comment]
Offed alarms don't seem to be updating at the speed set for the alarm. I actually thought it wasn't updating at all. When an alarm is offed, is it updating at the specified time interval?

**Comment by dllud** [comment]
When alarms are off they update only you open the alarm list (or tilt the screen, i.e. they update when the alarm list activity is drew).

**Comment by cicardia** [comment]
update should be the same as set in the alarm's settings
