### ISSUE TITLE
without permission litecoin addition

### ISSUE THREAD

**Issue by ghost** [andrefbsantos/boilr#301]
@dllud hi again
* **without your explicit consent** Litecoin id given at https://github.com/drpout/boilr#donations-and-tips was added by me in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13451/diffs#119f1789a099c224b7c40b61e6085a0432d12010
* should i remove it?
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417), [discussion 1](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) and [discussion 2](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13533#note_1504648422) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..

**Comment by dllud** [comment]
Hi @jindam-vani 

> should i remove it?
No. Please keep it.

And thanks for keeping our F-Droid data up-to-date!
