### ISSUE TITLE
Organize alarm list

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#50]
Alarms are displayed from newer to older. Is it possible to organize them manually?

**Comment by cicardia** [comment]
noticed, when I shut down an alarm it moves to first row of the alarm list. is this supposed?

**Comment by andrefbsantos** [comment]
Shut down by turning it off when the alarm triggers or by turning it off in the alarm list?

**Comment by cicardia** [comment]
By turning it off when it triggers
