### ISSUE TITLE
persistent no internet notification

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#55]
boilr's no internet notification is persistent even after you reconnect to the internet. shouldn't it be disappearing alone? I understand it might be useful for the user to know that the app was offline. but it also feels annoying having to check useless notifications all the time. What is your experience?

**Comment by andrefbsantos** [comment]
The no internet notification is removed by the first alarm which is able to retrieve its last value. Therefore, if you only have alarms with high update value, it may take a while to one of them check its last value and remove the no internet notification.

Could you check if that was the case?
