### ISSUE TITLE
Alarms don't shut off

### ISSUE THREAD

**Issue by duartebarbosa** [andrefbsantos/boilr#56]
I've been using boilr for the last couple of days and I've noticed that whenever a price limit has been achieved and an alarm starts, I'm able to shut the notification off by sliding it away on the lock screen but the alarm will continue to be audible.

To shut if off, I need to unlock the screen and kill the application. Checking/Unchecking the alarm button does not work.
I'm experiencing this on a Nexus 5 running plain vanilla AOSP 5.0.1.

**Comment by dllud** [comment]
Great. This confirms that bug is not an isolated problem of @cicardia 's phone.
I'll try to reproduce it on mine and fix it tomorrow.

**Comment by andrefbsantos** [comment]
>I'm able to shut the notification off by sliding it away on the lock screen but the alarm will continue to be audible.

When an alarm triggers, a screen is shown with the alarm's information and a button to turn it off. I'm not understanding how you slid the alarm screen when you have to press the turn off button to stop the alarm. What do you mean by "sliding it away"?

**Comment by andrefbsantos** [comment]
Duplicated of #10. Fixed with 8fb9886445b643ada422e112b27d2801fe2ba2ab.
