### ISSUE TITLE
redesign triggered alarm pannel

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#71]
![NotificationActivity-01](https://cloud.githubusercontent.com/assets/1716156/6274635/c3ff1b80-b870-11e4-9f75-7b0a65264f8c.PNG)
What do you think?

**Comment by dllud** [comment]
1. Pair and exchange should be the first information. According to you these are the most important bits of information and the ones the user needs to read before being able to interpret the price value. Also, it keeps coherence with the rest of the app.

2. Exchanging the "Turn off" button for the power icon seems ok and is useful for #24 where we need buttons with icons instead of text. However what do you do about "Keep monitoring" button?

3. Users will spend a long time before finding that text is clickable and takes them to different places. Remember the irritating sound you are hearing while seeing this activity. We should keep the activity simple and with a minimal number of actions.

**Comment by cicardia** [comment]
1. pair and exchange 1st. dead on!
2. the "keep monitoring" works? the user has to redefine alarm bounds before monitoring again. This won't happen in the event price inverted on the alarm bound, not probable.
3. if the text is underlined with a little blue line it will be easy to understand. perhaps the font color could be blue aswell.

**Comment by dllud** [comment]
2\. Keep monitoring only appears in Price Change alarms.
3\. Maybe just underline it in blue. Adding a blue font starts to turn this into an angry fruit salad.
4\. Why the direction arrow on top of the text? It is not the most important element. Keep it on the left or even on the right, it only serves for illustration purposes.

**Comment by cicardia** [comment]
2. hmm what if it keeps monitoring by default unless the user turns it off? the triggered alarm sound would stop as soon as the user interacts with the triggered alarm page. the same for price hit. no extra buttons or txt.
3.  true. i think underlining would be enough.
4. guys, we gotta start taking care of aesthetics & composition. The way it is now has composition errors.

**Comment by cicardia** [comment]
2. the power icon would turn off both price change or price hit alarms. The price change alarm would keep monitoring unless turned off by the user (power icon), either on the triggered alarm page or on the alarm list. Instead of a new dismiss button, we could make it simpler and make the alarm mute as soon as the user interacts. So when price change triggers, it rings till the user interacts. He then can turn off, go to settings, or go to the exchange. The sound is muted after first interaction.

4. WOW incredible link =P ermmm I'm not giving free online composition classes AHAHAH. I'll work on it a little more and we'll decide what works best later on. Good point! work both vert and hor.

**Comment by dllud** [comment]
2\. What do you mean by "as soon as user interacts"? A click somewhere? If so I won't implement it like that. Remember the discussion on #24, this activity pops-up even when screen was locked. We must avoid the user turning off the alarm inadvertently, e.g. while taking the phone out of his pocket, before reading what is on the screen. Therefore we need some sort of dismiss button.

**Comment by cicardia** [comment]
2. as soon as the user clicks on a link, or back button, or wtv. not just touching the screen, but interacting, doing something.

**Comment by dllud** [comment]
2\. Ok, that was assumed. Any click on something clickable on the notification activity closes the activity. Now imagine a Price Change alarm is triggered and the user just wants to dismiss it: she doesn't want to go to the exchange, she doesn't want to turn it off or change its settings. There must be a button for this because it will be the most common action with Price Change alarms: keep it monitoring and do nothing else.

**Comment by cicardia** [comment]
then i'd use the back button (and go to alarm list) or the menu button. I'm simply looking for solutions for not having extra buttons. creating a dismiss button and paste it side by side with the power button won't look good.

**Comment by dllud** [comment]
2\. Well, it will have to be. Hardware keys are a bad idea. The user will spend a long time figuring out they are the ones working. Better make it explicit with a button on the screen. Also the "won't look good" problem will only happen on smartphones running Android 3.0-4.1 (roughly 20% of the users). Once you design the icons I'll implement a GlowPadView for all users running Android 4.2+. With it having two buttons looks good:
![glowpad](https://cloud.githubusercontent.com/assets/1716156/6278757/69283afe-b891-11e4-9b74-644bb02c8ad3.png)

**Comment by cicardia** [comment]
we need a dismiss and turn off (a version of the power button)? android's stock icons:

1. dismiss -http://media02.hongkiat.com/android-notification-features/dismiss-all-notifications.jpg

2. as for the power button, i'd make a strip down version of the power button, without the blue rolling thing. Or we can use android's stock icon.

I'd use both icons without the glowpad for older android. What do you think?

**Comment by dllud** [comment]
Yup, that way. Now icons:

- Turn off
![ic_lock_power_off](https://cloud.githubusercontent.com/assets/1716156/6280252/f2297e52-b8a1-11e4-9522-576744068487.png)

- The other one I would rather call it "Keep monitoring" than "Dismiss" and would like an icon which reflects that. I think the reboot icon suits the case.
![ic_lock_reboot](https://cloud.githubusercontent.com/assets/1716156/6280266/21bfc388-b8a2-11e4-9713-d8064593f62b.png)

**Comment by cicardia** [comment]
nice, better than the dismiss icon! it would be confusing, it could mean delete or alike.

**Comment by cicardia** [comment]
@dllud I'm finishing the "positioning". I'll use the above two icons for the triggered alarm panel ok?

**Comment by dllud** [comment]
The screen arrangement was set when we last talked. No need for a sketch, I drew my own.

**Comment by cicardia** [comment]
send me, i need it for the "positioning"

**Comment by dllud** [comment]
You forgot the labels underneath the icons: Resume and Off. Won't that make it look a little better?

**Comment by cicardia** [comment]
no, the problem is with the composition. we'r creating a kind of ugly triangle with all the info on top and too little stupid eyes on the bottom

**Comment by dllud** [comment]
![trigger](https://cloud.githubusercontent.com/assets/1716156/6362715/2516c0d8-bc88-11e4-9fd2-b21ddb4b5600.png)

**Comment by cicardia** [comment]
LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL github is becoming way more interesting now!!! =D
@dllud I absolutely love your mouse drawing skills! :+1:
