### ISSUE TITLE
alerts "default" behavior

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#75]
alerts "default" behavior is to change already created alarms if the defaults are changed on the settings. The correct behavior would be to only apply the new default to newly created alarms. the existig ones shouldn't be changed.

**Comment by dllud** [comment]
Right, it is by no way evident that changing the default alert type/sound or vibrate will also affect all alarms that are using the default.

In order to change preferences on multiple alarms we should instead have something like a multi-editor, where the user could select multiple alarms to edit. That's something we will not implement soon because users set few alarms (2 to 4 I expect).

**Comment by cicardia** [comment]
I'd say most users would range from 2-6 alarms. I don't foresee any urgency on having a multi-editor.

**Comment by dllud** [comment]
But how about writing "Using app default" in the summary of Alarm type, Alarm sound and Vibrate preferences if nothing specific was set? Then the user would understand that those are using the app defaults and change with them.

It would look like this:
![app-defaults](https://cloud.githubusercontent.com/assets/1716156/6364492/b203f28e-bc9e-11e4-8e29-473175740d34.png)

I consider it a feature, the ability to have alarms tied to a default app setting.

**Comment by dllud** [comment]
Even better, I can show the defined value simultaneously:

![app-defaults2](https://cloud.githubusercontent.com/assets/1716156/6364543/a2545aa8-bc9f-11e4-9daa-37174d8900f4.png)

**Comment by cicardia** [comment]
that's confusing. and as said above, there's no need to multi edit anything, since most users won't have more than 4 or 6 alarms. besides, the effect you want would be reached by going to Boilr's settings, and changing the defaults. As for the alarm settings page, I'd leave it as it was.

**Comment by dllud** [comment]
Yes, that's how it is working right now, if you change the app defaults you change all alarms using the defaults. Isn't that useful if we make it visible like in the screenshot above?

**Comment by cicardia** [comment]
sorry i wasn't clear. what i mean is, if you change the defaults, then all new alarms will be as you want. the way it is right now isn't logical.

**Comment by dllud** [comment]
I asked @andrefbsantos opinion. He believes the currently implemented approach is what users expect. He pointed me towards the stock Contacts app. There you can define a specific ringtone for a given contact. If you set no ringtone it uses the default one and when you change the default all contacts using it change too.

Nonetheless I'm adding the "(app default)" comment to make it evident.

**Comment by cicardia** [comment]
OK, but IMHO that's not the standard "default" behaviour. I've never seen anything doing it like that. Plus, mingling with general settings should never change what you already defined for each alarm, even if it's using the default values. It's not logical.

But hey, just my 2cents.
-- 
<a href="http://cargocollective.com/algazarra" target="_blank">Algazarra</a>

**Comment by dllud** [comment]
@duartebarbosa suggestion: add default has an option in the list to make it even more explicit and allow user to switch back and forth to default.

![alert-defaults2](https://cloud.githubusercontent.com/assets/1716156/6405823/340360bc-be20-11e4-8f77-d0e744b81b00.jpg)
