### ISSUE TITLE
Exchange&pair no frame @ alarm list

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#76]
Its a shame we loose the homogeneous frame when the exchange name is so big. What other solutions do we have?
![dark-depois](https://cloud.githubusercontent.com/assets/7598320/6324371/12b7ffa4-bb31-11e4-92f2-3ee172941abe.png)

**Comment by dllud** [comment]
I can add inner padding but then we loose one more letter or so. Is it better that way?

**Comment by cicardia** [comment]
I think the frame should be homogeneous if we loose one letter there s no problem, but if we put the favicon it will loose another letter or 2

**Comment by dllud** [comment]
Done. I also made the frame a bit wider:

![pair exchange-frame1](https://cloud.githubusercontent.com/assets/1716156/6365584/cd6adde0-bcb1-11e4-87cd-ef86c5e7fde1.png) ![pair exchange-frame2](https://cloud.githubusercontent.com/assets/1716156/6365599/047b8be0-bcb2-11e4-90dd-af32e2c658fb.png)
![pair exchange-frame3](https://cloud.githubusercontent.com/assets/1716156/6365585/cd6fe920-bcb1-11e4-84e6-6d456b3acabe.png)

**Comment by cicardia** [comment]
please send me the apk for testing
