### ISSUE TITLE
persistent no internet notifications

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#79]
Joel noticed something, when Boilr has no internet connection it triggers a notification. If you dismiss it, Boilr will trigger a new no net notification as soon as an alarm tries to update. when dismissed, the notifications should stop. that is, the no internet notification should only show up once. Or at least make no sound after the first notification. check #61

**Comment by dllud** [comment]
I agree. But we must be careful. Imagine that a user dismisses a notification now. One hour later Boilr gets a network connection and alarms start working. Two hours later Boilr looses connection again: shouldn't we show a notification? I believe so. Therefore I would implement it in the following way:
- when user dismisses a notification: store the state `do NOT show no internet notifications`;
- when Boilr gets a network connection: store the state `show no internet notifications`.

Comments?

With this I think we can get rid of the "Show no internet warning" app preference. Do you agree?

**Comment by cicardia** [comment]
Yes. That's perfect. After reconnecting and disconnecting again, the no internet would pop up again.

If there are no connection changes, than just one notif
-- 
<a href="http://cargocollective.com/algazarra" target="_blank">Algazarra</a>

**Comment by cicardia** [comment]
And I think the warning icon on the status bar should be persistent if u have alarm on and no internet. Hmm but this might create some confusion. Let's take a break and reconsider the whole thing. There has to be a middleterm
-- 
<a href="http://cargocollective.com/algazarra" target="_blank">Algazarra</a>

**Comment by dllud** [comment]
>  the warning icon on the status bar should be persistent

Not good. Without the notification text the user might miss the icon meaning.

**Comment by cicardia** [comment]
Exactly. Maybe the best option is to just deactivate the notification sound after the first warning untill there's a connection status change. Only the first notification per connection loss would play a sound.

**Comment by dllud** [comment]
Currently we have no sound on notifications.

What Joel pointed out is that the notification on the drawer becomes annoying when it appears again after dismissing it. I think we should go for what we agreed on the beginning.

Or do you find it risky? The issue is: user dismisses notification, 3 hours later Boilr continues without connection, should a warning appear again?
Probably no, if she dismissed the notification it was her decision, therefore her problem.

**Comment by cicardia** [comment]
Does other apps notifications usually play sound?

If I press the menu button and dismiss Boilr, the no net notif doesn't stop appearing. That's the real problem.

IMHO as Boilr is working the no net should keep showing up. And when dismissed on menu, it should stop
-- 
<a href="http://cargocollective.com/algazarra" target="_blank">Algazarra</a>

**Comment by dllud** [comment]
> Does other apps notifications usually play sound?

It depends on how important they are. Usually there is sound for something you can and should immediately act upon, e.g. incoming SMS. For a not internet warning like in Boilr adding sound wouldn't follow this standard as most of the time there is nothing you can do about it.

> IMHO as Boilr is working the no net should keep showing up. And when dismissed on menu, it should stop

Agreed. Let's add one more rule to those detailed above:
- when alarm list is displayed: store the state `show no internet notifications`.

**Comment by cicardia** [comment]
I'd add that the first no internet notif has a little sound aswell.
I don't understand the "store the state show no internet notifications"

Algazarra <http://cargocollective.com/algazarra>

2015-02-25 21:13 GMT+00:00 David Ludovino <notifications@github.com>:

**Comment by andrefbsantos** [comment]
>I'd add that the first no internet notif has a little sound aswell.

The sound alert makes sense when the alert is part of chain of events and the user attention and actions are important to continue the flow of events, like receiving mail, IM or SMS. I don't think the no internet notification follows this logic, it's just a notification that doesn't require the user attention right on spot.

It also be annoying in situations of bad connection where boilr wouldn't have continuous connection.  

>I don't understand the "store the state show no internet notifications"

When the user opens Boilr and there is no internet connection, we will allow boilr to show a notification even when a notification was previously shown and dismissed.

**Comment by cicardia** [comment]
I agree with everything, but as a user it happens that we configure boilr, than leave the cellphone while working. If our net connection dies (or the cellphone changes to meo-wifi or fonzon, because it has better signal, and needs to login before getting access) we have no warning, and we'll only know it when we use the cellphone again. That's why I suggested the first time playing a sound. As a safeguard.

**Comment by andrefbsantos** [comment]
In that case my phone shows a notification and plays the alert sound reporting that he is connected but has no internet access. 

I believe that's the default behavior of android to produce that alert.

**Comment by cicardia** [comment]
I hope so, it should be like that. My SGS2 w/ replicant doesn't play anything, though I do get the notification.

**Comment by dllud** [comment]
My SGS2 with Replicant 4.2 also doesn't play any sound but shows a notification in the drawer. Furthermore, you get no sound notification when you loose connection and stay like that, i.e. your phone does not connect to any other network. Therefore adding sound may be a good feature.

The only con is this one:
> It also be annoying in situations of bad connection [...]. 

I'll add it and wait for user feedback.

**Comment by cicardia** [comment]
>The only con is this one:
>> It also be annoying in situations of bad connection [...]. 
>I'll add it and wait for user feedback.
what about a timer for the connection? If the connection doesn't hold for more than 5/15seconds, don't play the notif sound again, or something like that.

**Comment by dllud** [comment]
It would be better to set it to something like 1-2 min. Anyway, I am implementing this without the timer. I'll add it later if users complain.

**Comment by gabesbit** [comment]
What I am missing most, is an option to switch off internet notification. Let me explain. Mobile internet todays sucks. At least in my country. It is a mix of dfifferent techs like GPRS, EDGE, 3G, H depends on area where you move. This leads to many annoying notification "Check your connection". It happend I recieved 3 price notification, and 10 connection notification a day. Really annoying. It would be nice to simply turn this off. I dont care about connection. I know it sucks. When there is connection, app will get updates anyway. It shouldn't interrupt me in any way if I do not want to be notified about connection.

**Comment by algazarra** [comment]
What if we included a dismiss permanently button on the notification?

It would only alert about your connection when you restarted the app.

**Comment by dllud** [comment]
> What if we included a dismiss permanently button on the notification?

Good idea. Right now I just recovered the "Show no internet warning" setting we had before. Later, when working on #67, we can add a button to the notification.

Note: our previous idea of a timer to avoid annoying notifications on intermittent connections would never work properly. Finding the right time interval would be difficult. Notice I was thinking about "1-2 min" and @gabesbit says "10 connection notification a day" are already too annoying. Thus it's better to ask for user input with a setting/button.

**Comment by gabesbit** [comment]
Thanks, I will check this out in new version, then share again.
