### ISSUE TITLE
Substitute NaN for — when no price was fetched

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#80]
Joel also noticed that while the app hasn't gotten last price, it shows "Nan". that's confusing, specially since for cryptos we have new notations. can we replace the "nan" for "--" or "updating" or for example animate some dots in a line ". . . . . ." and sequentially give 0 alpha to one of the dots? know what I mean?

**Comment by dllud** [comment]
Forget about animations for now. Choose something static. I prefer a: — (Unicode U+2014).

**Comment by cicardia** [comment]
perfect
