### ISSUE TITLE
Preferences fragments with malformed theme after screen rotation

### ISSUE THREAD

**Issue by dllud** [andrefbsantos/boilr#83]
Before rotation (correct theme):

![before-rotation1](https://cloud.githubusercontent.com/assets/1716156/6366153/6cc01494-bcb9-11e4-8fe3-59989ae8c1a5.png) ![before-rotation2](https://cloud.githubusercontent.com/assets/1716156/6366152/6cbfd7a4-bcb9-11e4-9b9d-d8ce851ec789.png)

After rotation (screen was put in horizontal mode and back to vertical):

![after-rotation1](https://cloud.githubusercontent.com/assets/1716156/6366166/858876f6-bcb9-11e4-9a14-58405dbbe81b.png) ![after-rotation2](https://cloud.githubusercontent.com/assets/1716156/6366165/85859ef4-bcb9-11e4-84d2-c72a1a5ebeab.png)

This bug was introduced when we added the [UndoBar](https://github.com/soarcn/UndoBar).

**Comment by cicardia** [comment]
looks nasty! uggly yellow & white.
