### ISSUE TITLE
support btc.sx

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#89]
BTC.sx is an easy-to-use Bitcoin Trading Platform. From one account, we enable our users to place Long or Short leveraged trades across multiple exchanges using our position management features.

Unlike trading with a regular exchange, your trades made through us are directly executed out to market; removing the need for internally matching your orders against other clients.

Since we do not allow users to trade orders off of one another, direct execution of positions during volatile periods are therefore guaranteed.

**Comment by andrefbsantos** [comment]
Aggregator for BitStamp, itBit and Bitfinex.
